name: Update Available TOML
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours, at the start of the hour

jobs:
  update_available_toml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up hysp-pkg-updater
        run: |
          if ! command -v aria2c &>/dev/null; then
              sudo apt update
              sudo apt install -y aria2
          fi
          aria2c https://github.com/metis-os/hysp-pkg-updater/releases/download/v0.1.0/hysp-pkg-updater-0.1.0-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf hysp-pkg-updater-0.1.0-x86_64-unknown-linux-gnu.tar.gz
          chmod +x hysp-pkg-updater-0.1.0/hysp-pkg-updater
          mv hysp-pkg-updater-0.1.0/hysp-pkg-updater .

      - name: Update available.toml
        run: |
          ./hysp-pkg-updater && rm hysp-pkg-updater 
          mv available-bk.toml available.toml

      - name: Clean up downloaded files
        run: |
          rm -rf hysp-pkg-updater-0.1.0*
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add . 
          git commit -am "chore(available): updated available.toml thx hysp-pkg-updater"
          git push --force

